openapi: 3.0.0
info:
  title: API documentation
  version: 1.0.0
  schemes:
    - http
servers:
  - url: http://0.0.0.0:8081
tags:
  - name: matching
paths:
  /matching:
    $ref: './resources/matching.yaml#/matching'   
      
components:
  schemas:
    Drivers:
      $ref: './schemas/matching_schema.yaml'

